### ISSUE TITLE
Ongoing issue with empty CSV files generated by an API query

### ISSUE THREAD

**Issue by SJ-bond** [IATI/IATI-Datastore#241]
Hi there, I've previously used both an API query (http://datastore.iatistandard.org/api/1/activity.csv?reporting-org=GB-CHC-115790&stream=Truehttp://datastore.iatistandard.org/api/1/access/activity.csv?reporting-org=GB-CHC-1049160&stream=Truehttp://datastore.iatistandard.org/api/1/access/activity.csv?reporting-org=GB-CHC-261488&stream=True) and the Query Builder at http://datastore.iatistandard.org/query/index.php to pull off Anti Slavery International's activity data. I tried it again yesterday as I wanted to explain to ASI how to do it, and it's returning a csv with no data in (see attached). I tried it again today and still no joy. When I run the query (not the query builder) I get an error message:

Not Found

The requested URL was not found on the server.

If you entered the URL manually please check your spelling and try again.

**Comment by dalepotter** [comment]
Hi Sarah, there's an ongoing issue with data from Aidstream not correctly importing into the Datastore due to a server configuration issue.  We're in touch with their support helpdesk about this and we will be chasing up this week.

In the meantime, it is possible to access Anti-Slavery International's data using the Registry (this takes the data from the 2 activities in their [Anti-Slavery International Activity file](http://iatiregistry.org/dataset/asil-activities) and converts to CSV: http://tools.aidinfolabs.org/csv/direct_from_registry/index.php (The URL to input in the `Raw data address` field is: `https://www.aidstream.org/files/xml/asil-activities.xml`):

![image](https://cloud.githubusercontent.com/assets/8247168/13643047/ddfa0a70-e616-11e5-905d-5ca2da6c3285.png)

**Comment by andylolz** [comment]
This looks closable, since the query now works:
http://datastore.iatistandard.org/api/1/access/activity.csv?reporting-org=GB-CHC-1049160

**Comment by dalepotter** [comment]
Thanks for flagging @andylolz 

The above-linked CSV output is now showing 2 results, the same as the number of activities in their only [activity file](https://aidstream.org/files/xml/asil-activities.xml).

Therefore I am marking this one as closed :-)
